### ISSUE TITLE
x6-angular-shape@1.x不支持ngOnChanges有没有解决方法？

### ISSUE THREAD

**Issue by chenlong-io** [Eve-Sama/ngx-x6-demo#3]
如果有hack方法，还请大佬给个简单示例，大佬万岁！！！🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by Eve-Sama** [comment]
也许有办法,  但是得试一试. 我最近很忙, 周末帮你看下可以吗

**Comment by chenlong-io** [comment]
@Eve-Sama E 可以的，麻烦大佬了🙏🏻🙏🏻🙏🏻

**Comment by chenlong-io** [comment]
> 也许有办法, 但是得试一试. 我最近很忙, 周末帮你看下可以吗

@Eve-Sama 大佬~~~~~~~~~~~ 看到请回答 看到请回答~~~~

**Comment by Eve-Sama** [comment]
不好意思 周末忘记看了 今晚我看下吧 也只能是试一下 不确定能不能做

**Comment by Eve-Sama** [comment]
可以升级2.x吗? 我看了下1.x, 源码和demo都没有2.x写的好

**Comment by Eve-Sama** [comment]
我把2.x的写法挪过来了, 能正常运行, 我写了demo 你看下这个PR. 但是目前你应该只能拷贝我源码里shape的代码. 如果想用x6官方的1.x, 得等一等了, 我暂时没时间给他们提pr. 太忙了.
